# Generated by Django 5.1.3 on 2024-12-13 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_de_usuario',
            new_name='username',
        ),
    ]
