# Generated by Django 5.1.3 on 2024-12-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion_producto',
            field=models.CharField(default='Sin descripción', max_length=9999),
        ),
    ]
